# Generated by Django 5.2.8 on 2025-11-07 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_vendor_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
            preserve_default=False,
        ),
    ]
