# Generated by Django 5.2.8 on 2025-11-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_product_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Vendor',
            new_name='vendor',
        ),
    ]
